
    <script>
        /** RCM Google Analytics TEST */
        // pseudo ga
        var ga = function(a) {
            // do nothing
        };

        /**
        <?php
        if ($this->model->hasTracking()) {
            echo "\n";
            echo "        Analytics for this site: \n";
            echo "          id: {$this->model->getId()} \n";
            echo "          trackingId: {$this->model->getTrackingId()} \n";
            echo "          verificationCode: {$this->model->getVerificationCode()} \n";
            echo "          siteId: {$this->model->getSiteId()} \n";
            echo "\n";
        } else {
            echo "\n";
            echo "        No Analytics set for this site\n";
            echo "\n";
        }
        ?>
        */
    </script>
